// <auto-generated />
using System;
using DataAccessLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251220130858_addImageColumn")]
    partial class addImageColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Models.AdditionalTextBook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BookFilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("AdditionalTextBooks");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasDiscriminator<string>("AnswerType").HasValue("Answer");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DataAccessLayer.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAccountDisabled")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "default-admin-id",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1d3f76ae-3b48-450c-931f-389c95a470d0",
                            Email = "calvintshabalala9@gmail.com",
                            EmailConfirmed = true,
                            IsAccountDisabled = false,
                            LockoutEnabled = false,
                            Name = "Admin",
                            NormalizedEmail = "CALVINTSHABALALA9@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEO30xzS570w8Tx8qFemEa1lONPMMyKA140Fng+3tt9/Jlaq39fJtT15/7fhd7hkY3A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "19567588-92f3-4192-8fbb-de7f67d1ae55",
                            Surname = "User",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.Chapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("int");

                    b.Property<string>("ChapterTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TermId");

                    b.ToTable("Chapters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ChapterNumber = 1,
                            ChapterTitle = "Introduction to Biology",
                            Description = "Basic concepts of biology.",
                            SubjectId = new Guid("5a5da2f4-f649-4994-95b1-228b82e9d98c"),
                            TermId = new Guid("aa10883b-b521-4c82-8cf5-7dfb4215ebe4")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            ChapterNumber = 2,
                            ChapterTitle = "Cell Structure",
                            Description = "Understanding the building blocks of life.",
                            SubjectId = new Guid("5a5da2f4-f649-4994-95b1-228b82e9d98c"),
                            TermId = new Guid("aa10883b-b521-4c82-8cf5-7dfb4215ebe4")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            ChapterNumber = 3,
                            ChapterTitle = "Genetics",
                            Description = "Introduction to genetics.",
                            SubjectId = new Guid("5a5da2f4-f649-4994-95b1-228b82e9d98c"),
                            TermId = new Guid("aa10883b-b521-4c82-8cf5-7dfb4215ebe4")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            ChapterNumber = 4,
                            ChapterTitle = "Evolution",
                            Description = "Theory of evolution.",
                            SubjectId = new Guid("5a5da2f4-f649-4994-95b1-228b82e9d98c"),
                            TermId = new Guid("aa10883b-b521-4c82-8cf5-7dfb4215ebe4")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            ChapterNumber = 5,
                            ChapterTitle = "Ecology",
                            Description = "Ecosystems and environment.",
                            SubjectId = new Guid("5a5da2f4-f649-4994-95b1-228b82e9d98c"),
                            TermId = new Guid("aa10883b-b521-4c82-8cf5-7dfb4215ebe4")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            ChapterNumber = 6,
                            ChapterTitle = "Human Body",
                            Description = "Human anatomy and physiology.",
                            SubjectId = new Guid("5a5da2f4-f649-4994-95b1-228b82e9d98c"),
                            TermId = new Guid("aa10883b-b521-4c82-8cf5-7dfb4215ebe4")
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            ChapterNumber = 7,
                            ChapterTitle = "Plant Biology",
                            Description = "Plant structure and function.",
                            SubjectId = new Guid("5a5da2f4-f649-4994-95b1-228b82e9d98c"),
                            TermId = new Guid("aa10883b-b521-4c82-8cf5-7dfb4215ebe4")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            ChapterNumber = 8,
                            ChapterTitle = "Microbiology",
                            Description = "Microorganisms and their roles.",
                            SubjectId = new Guid("5a5da2f4-f649-4994-95b1-228b82e9d98c"),
                            TermId = new Guid("aa10883b-b521-4c82-8cf5-7dfb4215ebe4")
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            ChapterNumber = 9,
                            ChapterTitle = "Biotechnology",
                            Description = "Applications of biology.",
                            SubjectId = new Guid("5a5da2f4-f649-4994-95b1-228b82e9d98c"),
                            TermId = new Guid("aa10883b-b521-4c82-8cf5-7dfb4215ebe4")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            ChapterNumber = 10,
                            ChapterTitle = "Conservation",
                            Description = "Conservation of biodiversity.",
                            SubjectId = new Guid("5a5da2f4-f649-4994-95b1-228b82e9d98c"),
                            TermId = new Guid("aa10883b-b521-4c82-8cf5-7dfb4215ebe4")
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.ChapterSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentSectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("ParentSectionId");

                    b.ToTable("ChapterSections");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1"),
                            ChapterId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Content = "What is Biology?",
                            Order = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a2a2a2a2-a2a2-a2a2-a2a2-a2a2a2a2a2a2"),
                            ChapterId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Content = "Biology is the study of living organisms.",
                            Order = 2,
                            ParentSectionId = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("a3a3a3a3-a3a3-a3a3-a3a3-a3a3a3a3a3a3"),
                            ChapterId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Content = "Cell Structure Overview",
                            Order = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a4a4a4a4-a4a4-a4a4-a4a4-a4a4a4a4a4a4"),
                            ChapterId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Content = "Cells are the basic units of life.",
                            Order = 2,
                            ParentSectionId = new Guid("a3a3a3a3-a3a3-a3a3-a3a3-a3a3a3a3a3a3"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("a5a5a5a5-a5a5-a5a5-a5a5-a5a5a5a5a5a5"),
                            ChapterId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Content = "Introduction to Genetics",
                            Order = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a6a6a6a6-a6a6-a6a6-a6a6-a6a6a6a6a6a6"),
                            ChapterId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Content = "Genes are units of heredity.",
                            Order = 2,
                            ParentSectionId = new Guid("a5a5a5a5-a5a5-a5a5-a5a5-a5a5a5a5a5a5"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("a7a7a7a7-a7a7-a7a7-a7a7-a7a7a7a7a7a7"),
                            ChapterId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Content = "Theory of Evolution",
                            Order = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a8a8a8a8-a8a8-a8a8-a8a8-a8a8a8a8a8a8"),
                            ChapterId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Content = "Evolution explains diversity.",
                            Order = 2,
                            ParentSectionId = new Guid("a7a7a7a7-a7a7-a7a7-a7a7-a7a7a7a7a7a7"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("a9a9a9a9-a9a9-a9a9-a9a9-a9a9a9a9a9a9"),
                            ChapterId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Content = "Ecosystems",
                            Order = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("b1b1b1b1-b1b1-b1b1-b1b1-b1b1b1b1b1b1"),
                            ChapterId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Content = "Ecosystems are communities of organisms.",
                            Order = 2,
                            ParentSectionId = new Guid("a9a9a9a9-a9a9-a9a9-a9a9-a9a9a9a9a9a9"),
                            Type = 2
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("ForumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Upvotes")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ForumId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Forum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DiscussionQuestion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Screenshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Forums");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f9f64363-aaf3-446e-a8a2-e81aa0e061a3"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscussionQuestion = "What are common algebra problems students face?",
                            SubjectId = new Guid("3fe2283b-6751-4633-8903-2043997bbf20"),
                            Topic = "Difficult problems in Algebra"
                        },
                        new
                        {
                            Id = new Guid("0e8e0ea0-3d5b-4786-94e1-d33178d04378"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscussionQuestion = "How do we understand Newton’s Laws?",
                            SubjectId = new Guid("b2df6db3-2b38-4c3a-9517-5e3e2b98b741"),
                            Topic = "Physics Chapter 1"
                        },
                        new
                        {
                            Id = new Guid("d63f64ac-9de0-4098-9e64-482d9008f5bb"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscussionQuestion = "What are the best study guides for exam preparation?",
                            SubjectId = new Guid("b2df6db3-2b38-4c3a-9517-5e3e2b98b741"),
                            Topic = "Best study guides?"
                        },
                        new
                        {
                            Id = new Guid("f2e1a133-5ba0-4c3c-b2ee-3e9f25a16a33"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscussionQuestion = "How should I approach exam preparation effectively?",
                            SubjectId = new Guid("b2df6db3-2b38-4c3a-9517-5e3e2b98b741"),
                            Topic = "Exam preparation tips"
                        },
                        new
                        {
                            Id = new Guid("f7a3ea3e-f2bd-4772-be50-55a663791746"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiscussionQuestion = "What are common algebra problems students face?",
                            SubjectId = new Guid("b2df6db3-2b38-4c3a-9517-5e3e2b98b741"),
                            Topic = "Difficult problems in Algebra"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b714b815-d0b2-4101-bfac-0364de42d14d"),
                            Name = "Grade 9"
                        },
                        new
                        {
                            Id = new Guid("3e71747b-dbc9-4e4f-a34d-d4ceed2c809b"),
                            Name = "Grade 10"
                        },
                        new
                        {
                            Id = new Guid("09a00c75-3063-4f32-8033-ad78188d2ec6"),
                            Name = "Grade 11"
                        },
                        new
                        {
                            Id = new Guid("a4641e89-a22d-4c52-beea-56e38f38227a"),
                            Name = "Grade 12"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.GradeSubject", b =>
                {
                    b.Property<Guid>("GradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GradeId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("GradeSubjects");
                });

            modelBuilder.Entity("DataAccessLayer.Models.PastMemorandum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PastPaperId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PastPaperId")
                        .IsUnique();

                    b.ToTable("PastMemorandums");
                });

            modelBuilder.Entity("DataAccessLayer.Models.PastPaper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("YearId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("YearId");

                    b.ToTable("PastPapers");
                });

            modelBuilder.Entity("DataAccessLayer.Models.PastPaperMemorandum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PastMemorandumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PastPaperId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PastMemorandumId");

                    b.HasIndex("PastPaperId");

                    b.ToTable("PastPaperMemorandums");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PointValue")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("QuestionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("QuestionTypeId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("DataAccessLayer.Models.QuestionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("QuestionTypes");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrescribedTextBook")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PrescribedTextBookFileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SubjectDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SubjectImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5a5da2f4-f649-4994-95b1-228b82e9d98c"),
                            Name = "Mathematics",
                            PrescribedTextBook = "MathBook.pdf",
                            PrescribedTextBookFileUrl = "",
                            SubjectDescription = "Math Description",
                            SubjectImageUrl = ""
                        },
                        new
                        {
                            Id = new Guid("4b1e2df5-c5ad-488e-94d6-b249d1016c40"),
                            Name = "Science",
                            PrescribedTextBook = "Physics Textbook",
                            PrescribedTextBookFileUrl = "",
                            SubjectDescription = "Science Description",
                            SubjectImageUrl = ""
                        },
                        new
                        {
                            Id = new Guid("c62a461a-0ab8-4bd7-83c4-a1bbb56a4772"),
                            Name = "Geography",
                            PrescribedTextBook = "Geography Textbook",
                            PrescribedTextBookFileUrl = "",
                            SubjectDescription = "Geography Description",
                            SubjectImageUrl = ""
                        },
                        new
                        {
                            Id = new Guid("8bae0fe9-7853-4d3d-949c-b5537303f330"),
                            Name = "Life Science",
                            PrescribedTextBook = "Biology Textbook",
                            PrescribedTextBookFileUrl = "",
                            SubjectDescription = "Life Science Description",
                            SubjectImageUrl = ""
                        },
                        new
                        {
                            Id = new Guid("948e6d61-8d75-46ca-8701-8921979eb1fa"),
                            Name = "Chemistry",
                            PrescribedTextBook = "Chemistry Textbook",
                            PrescribedTextBookFileUrl = "",
                            SubjectDescription = "Chemistry Description",
                            SubjectImageUrl = ""
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.SubjectYear", b =>
                {
                    b.Property<Guid>("YearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("YearId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("SubjectYears");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Term", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Terms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fc977587-a042-4037-bf45-a11551288e2e"),
                            Duration = "Jan - Mar",
                            Name = "Term 1"
                        },
                        new
                        {
                            Id = new Guid("e791d99e-2a6f-4792-b02e-5472b718a54e"),
                            Duration = "Apr - Jun",
                            Name = "Term 2"
                        },
                        new
                        {
                            Id = new Guid("49ce4c31-f032-450b-ac81-9950c8052a46"),
                            Duration = "Jul - Sep",
                            Name = "Term 3"
                        },
                        new
                        {
                            Id = new Guid("f918359a-498f-46c3-8928-1c4317b78af7"),
                            Duration = "Oct - Dec",
                            Name = "Term 4"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.TermYear", b =>
                {
                    b.Property<Guid>("TermId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("YearId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TermId", "YearId");

                    b.HasIndex("YearId");

                    b.ToTable("TermYears");
                });

            modelBuilder.Entity("DataAccessLayer.Models.TextbookFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("TextbookFiles");
                });

            modelBuilder.Entity("DataAccessLayer.Models.UserReaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Like")
                        .HasColumnType("bit");

                    b.Property<bool>("Upvote")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId");

                    b.ToTable("UserReactions");
                });

            modelBuilder.Entity("DataAccessLayer.Models.VideoTutorial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VideoName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("VideoPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("VideoTutorials");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ddb92a36-c523-4ad0-af07-be8d64670dbc",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "b714b815-d0b2-4101-bfac-0364de42d14d",
                            Name = "Guest User",
                            NormalizedName = "GUEST USER"
                        },
                        new
                        {
                            Id = "3e71747b-dbc9-4e4f-a34d-d4ceed2c809b",
                            Name = "Guest User",
                            NormalizedName = "STUDENT USER"
                        },
                        new
                        {
                            Id = "e232ef54-a5b1-4769-8095-bced0fd28df5",
                            Name = "Premium User",
                            NormalizedName = "PREMIUM USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Year", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("YearNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Years");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fdac523c-00e2-4ffe-9497-5cdab5959335"),
                            YearNumber = 2020
                        },
                        new
                        {
                            Id = new Guid("090fc745-6b53-42af-a2f0-3442f3280d2f"),
                            YearNumber = 2021
                        },
                        new
                        {
                            Id = new Guid("aa462ed6-bdf7-4b82-8e84-43c6f78a84a9"),
                            YearNumber = 2022
                        },
                        new
                        {
                            Id = new Guid("8fceb78d-6b28-4eae-8a7e-db9d5912cbc1"),
                            YearNumber = 2023
                        },
                        new
                        {
                            Id = new Guid("e11906d0-7520-411a-aa3b-fdee890ccd29"),
                            YearNumber = 2024
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.MultipleChoiceAnswer", b =>
                {
                    b.HasBaseType("DataAccessLayer.Models.Answer");

                    b.Property<string>("CorrectOption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("MultipleChoice");
                });

            modelBuilder.Entity("DataAccessLayer.Models.TrueFalseAnswer", b =>
                {
                    b.HasBaseType("DataAccessLayer.Models.Answer");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsTrue")
                        .HasColumnType("bit");

                    b.ToTable("Answers", t =>
                        {
                            t.Property("Explanation")
                                .HasColumnName("TrueFalseAnswer_Explanation");
                        });

                    b.HasDiscriminator().HasValue("TrueFalse");
                });

            modelBuilder.Entity("DataAccessLayer.Models.AdditionalTextBook", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Subject", "Subject")
                        .WithMany("AdditionalTextBooks")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Answer", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Chapter", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Subject", "Subject")
                        .WithMany("Chapters")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Term", "Term")
                        .WithMany("Chapters")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ChapterSection", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Chapter", "Chapter")
                        .WithMany("Sections")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.ChapterSection", "ParentSection")
                        .WithMany("ChildSections")
                        .HasForeignKey("ParentSectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Chapter");

                    b.Navigation("ParentSection");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Comment", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Forum", "Forum")
                        .WithMany("Comments")
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DataAccessLayer.Models.ApplicationUser", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Forum");

                    b.Navigation("ParentComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Forum", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Subject", "Subject")
                        .WithMany("Forums")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("DataAccessLayer.Models.GradeSubject", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Grade", "Grade")
                        .WithMany("GradeSubjects")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Subject", "Subject")
                        .WithMany("GradeSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("DataAccessLayer.Models.PastMemorandum", b =>
                {
                    b.HasOne("DataAccessLayer.Models.PastPaper", "PastPaper")
                        .WithOne("PastMemorandum")
                        .HasForeignKey("DataAccessLayer.Models.PastMemorandum", "PastPaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PastPaper");
                });

            modelBuilder.Entity("DataAccessLayer.Models.PastPaper", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Subject", "Subject")
                        .WithMany("PastPapers")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Year", "Year")
                        .WithMany("PastPapers")
                        .HasForeignKey("YearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Year");
                });

            modelBuilder.Entity("DataAccessLayer.Models.PastPaperMemorandum", b =>
                {
                    b.HasOne("DataAccessLayer.Models.PastMemorandum", "PastMemorandum")
                        .WithMany("PastPaperMemorandums")
                        .HasForeignKey("PastMemorandumId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.PastPaper", "PastPaper")
                        .WithMany()
                        .HasForeignKey("PastPaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PastMemorandum");

                    b.Navigation("PastPaper");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Question", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Chapter", "Chapter")
                        .WithMany("Questions")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.QuestionType", "QuestionType")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("QuestionType");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SubjectYear", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Subject", "Subject")
                        .WithMany("SubjectYears")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Year", "Year")
                        .WithMany("SubjectYears")
                        .HasForeignKey("YearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Year");
                });

            modelBuilder.Entity("DataAccessLayer.Models.TermYear", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Term", "Term")
                        .WithMany("TermYears")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Year", "Year")
                        .WithMany("TermYears")
                        .HasForeignKey("YearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Term");

                    b.Navigation("Year");
                });

            modelBuilder.Entity("DataAccessLayer.Models.TextbookFile", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Subject", "Subject")
                        .WithMany("TextbookFiles")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("DataAccessLayer.Models.UserReaction", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Comment", "Comment")
                        .WithMany("UserReactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.ApplicationUser", "User")
                        .WithMany("UserReactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Models.VideoTutorial", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Subject", "Subject")
                        .WithMany("VideoTutorials")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.ApplicationUser", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("UserReactions");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Chapter", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ChapterSection", b =>
                {
                    b.Navigation("ChildSections");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Comment", b =>
                {
                    b.Navigation("Replies");

                    b.Navigation("UserReactions");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Forum", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Grade", b =>
                {
                    b.Navigation("GradeSubjects");
                });

            modelBuilder.Entity("DataAccessLayer.Models.PastMemorandum", b =>
                {
                    b.Navigation("PastPaperMemorandums");
                });

            modelBuilder.Entity("DataAccessLayer.Models.PastPaper", b =>
                {
                    b.Navigation("PastMemorandum");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("DataAccessLayer.Models.QuestionType", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Subject", b =>
                {
                    b.Navigation("AdditionalTextBooks");

                    b.Navigation("Chapters");

                    b.Navigation("Forums");

                    b.Navigation("GradeSubjects");

                    b.Navigation("PastPapers");

                    b.Navigation("SubjectYears");

                    b.Navigation("TextbookFiles");

                    b.Navigation("VideoTutorials");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Term", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("TermYears");
                });

            modelBuilder.Entity("Year", b =>
                {
                    b.Navigation("PastPapers");

                    b.Navigation("SubjectYears");

                    b.Navigation("TermYears");
                });
#pragma warning restore 612, 618
        }
    }
}
